import type { Assumptions, RenameRow, Review } from './types';

export interface StagedRename extends RenameRow {
  temporary: string;
}

function hash(value: string): string {
  let result = 2166136261;
  for (const char of value) {
    result ^= char.codePointAt(0) ?? 0;
    result = Math.imul(result, 16777619);
  }
  return (result >>> 0).toString(36).padStart(7, '0').slice(0, 7);
}

export function stageRows(rows: RenameRow[]): StagedRename[] {
  return rows.filter((row) => row.current && row.next && row.current !== row.next).map((row, index) => {
    const normalized = row.current.replaceAll('\\', '/');
    const slash = normalized.lastIndexOf('/');
    const directory = slash >= 0 ? normalized.slice(0, slash + 1) : '';
    const basename = normalized.slice(slash + 1);
    return { ...row, temporary: `${directory}.rpr-${hash(`${row.current}\u0000${row.next}\u0000${index}`)}-${basename}` };
  });
}

const sh = (value: string): string => `'${value.replaceAll("'", `'"'"'`)}'`;
const ps = (value: string): string => `'${value.replaceAll("'", "''")}'`;

function untouchedTargets(staged: StagedRename[], caseInsensitive: boolean): string[] {
  const key = (value: string) => caseInsensitive ? value.toLocaleLowerCase('en-US') : value;
  const sources = new Set(staged.map((row) => key(row.current)));
  return staged.map((row) => row.next).filter((target) => !sources.has(key(target)));
}

function targetDirectories(staged: StagedRename[]): string[] {
  return [...new Set(staged.map((row) => row.next.replaceAll('\\', '/')).map((target) => {
    const slash = target.lastIndexOf('/');
    return slash >= 0 ? target.slice(0, slash) : '';
  }).filter(Boolean))];
}

export function shellPlan(rows: RenameRow[], assumptions: Assumptions, live: boolean): string {
  const staged = stageRows(rows);
  const move = (from: string, to: string) => live ? `mv -- ${sh(from)} ${sh(to)}` : `printf '%s\\n' ${sh(`mv -- ${sh(from)} ${sh(to)}`)}`;
  return [
    '#!/bin/sh',
    '# Generated by Rename Plan Reviewer. Run from the reviewed root folder.',
    `# Mode: ${live ? 'LIVE — this changes files' : 'DRY RUN — prints commands only'}`,
    'set -eu',
    '',
    '# Preflight: stop before touching anything if assumptions do not match.',
    ...staged.map((row) => `[ -e ${sh(row.current)} ] || { printf '%s\\n' ${sh(`Missing source: ${row.current}`)} >&2; exit 1; }`),
    ...staged.map((row) => `[ ! -e ${sh(row.temporary)} ] && [ ! -L ${sh(row.temporary)} ] || { printf '%s\\n' ${sh(`Temporary path already exists: ${row.temporary}`)} >&2; exit 1; }`),
    ...untouchedTargets(staged, assumptions.caseInsensitive).map((target) => `[ ! -e ${sh(target)} ] && [ ! -L ${sh(target)} ] || { printf '%s\\n' ${sh(`Destination already exists: ${target}`)} >&2; exit 1; }`),
    ...targetDirectories(staged).map((directory) => `[ -d ${sh(directory)} ] || { printf '%s\\n' ${sh(`Destination folder is missing: ${directory}`)} >&2; exit 1; }`),
    '',
    '# Phase 1: move every source aside so swaps and cycles cannot overwrite.',
    ...staged.map((row) => move(row.current, row.temporary)),
    '',
    '# Phase 2: place every temporary file at its reviewed destination.',
    ...staged.map((row) => move(row.temporary, row.next)),
    '',
    `printf '%s\\n' ${sh(live ? `Applied ${staged.length} renames.` : `Dry run only. ${staged.length} renames would be applied.`)}`,
    ''
  ].join('\n');
}

export function powershellPlan(rows: RenameRow[], assumptions: Assumptions, live: boolean): string {
  const staged = stageRows(rows);
  const move = (from: string, to: string) => live ? `Move-Item -LiteralPath ${ps(from)} -Destination ${ps(to)} -ErrorAction Stop` : `Write-Output ${ps(`Move-Item -LiteralPath ${ps(from)} -Destination ${ps(to)}`)}`;
  return [
    '# Generated by Rename Plan Reviewer. Run from the reviewed root folder.',
    `# Mode: ${live ? 'LIVE — this changes files' : 'DRY RUN — prints commands only'}`,
    "$ErrorActionPreference = 'Stop'",
    '',
    '# Preflight: stop before touching anything if assumptions do not match.',
    ...staged.map((row) => `if (-not (Test-Path -LiteralPath ${ps(row.current)})) { throw ${ps(`Missing source: ${row.current}`)} }`),
    ...staged.map((row) => `if (Test-Path -LiteralPath ${ps(row.temporary)}) { throw ${ps(`Temporary path already exists: ${row.temporary}`)} }`),
    ...untouchedTargets(staged, assumptions.caseInsensitive).map((target) => `if (Test-Path -LiteralPath ${ps(target)}) { throw ${ps(`Destination already exists: ${target}`)} }`),
    ...targetDirectories(staged).map((directory) => `if (-not (Test-Path -LiteralPath ${ps(directory)} -PathType Container)) { throw ${ps(`Destination folder is missing: ${directory}`)} }`),
    '',
    '# Phase 1: move every source aside so swaps and cycles cannot overwrite.',
    ...staged.map((row) => move(row.current, row.temporary)),
    '',
    '# Phase 2: place every temporary file at its reviewed destination.',
    ...staged.map((row) => move(row.temporary, row.next)),
    '',
    `Write-Output ${ps(live ? `Applied ${staged.length} renames.` : `Dry run only. ${staged.length} renames would be applied.`)}`,
    ''
  ].join('\n');
}

export function undoManifest(review: Review, assumptions: Assumptions): string {
  const staged = stageRows(review.rows);
  return JSON.stringify({
    format: 'rename-plan-reviewer/undo-v1',
    generatedAt: new Date().toISOString(),
    safeAtExport: review.safe,
    assumptions,
    warnings: review.findings.filter((finding) => finding.severity !== 'note'),
    undo: staged.map((row) => ({ current: row.next, new: row.current })),
    reviewedPlan: staged.map(({ current, next, line }) => ({ current, new: next, sourceLine: line }))
  }, null, 2);
}

export function planBundle(review: Review, assumptions: Assumptions): string {
  return JSON.stringify({
    format: 'rename-plan-reviewer/plan-v1',
    exportedAt: new Date().toISOString(),
    assumptions,
    rows: review.rows.map(({ current, next }) => ({ current, new: next })),
    findings: review.findings
  }, null, 2);
}

export function reviewPacket(review: Review, assumptions: Assumptions, live: boolean, inputErrors: readonly string[] = []): string {
  if (!review.safe || inputErrors.length > 0) {
    throw new Error('Resolve every error finding before exporting scripts.');
  }

  return `# Rename review packet\n\nGenerated ${new Date().toISOString()}\n\n## Findings\n\n\`\`\`json\n${planBundle(review, assumptions)}\n\`\`\`\n\n## Shell plan\n\n\`\`\`sh\n${shellPlan(review.rows, assumptions, live)}\n\`\`\`\n\n## PowerShell plan\n\n\`\`\`powershell\n${powershellPlan(review.rows, assumptions, live)}\n\`\`\`\n`;
}
